import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { GeolocationProvider } from "../../contexts/GeolocationContext";
import { ConvexClientProvider } from "./ConvexClientProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Firescape",
  description: "Generated by create next app",
  icons: {
    icon: "logo.png", // or "/favicon.png" if you're using a PNG
    shortcut: "logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GeolocationProvider>
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </GeolocationProvider>
      </body>
    </html>
  );
}
